services:
  h10:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: h10
    command: ["bash", "-lc", "ip route del default || true; ip route add default via 10.10.10.1 dev eth0 || true; sleep infinity"]
    networks:
      vlan10: {}

  h20:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: h20
    command: ["bash", "-lc", "ip route del default || true; ip route add default via 10.20.20.1 dev eth0 || true; sleep infinity"]
    networks:
      vlan20: {}
