version: "3.9"
services:
  r1:
    build: .
    container_name: r1
    ports:
      - "10161:161/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:false
  r2:
    build: .
    container_name: r2
    ports:
      - "20161:161/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:false
