services:
  r1:
    networks:
      mgmtnet:
        ipv4_address: 192.168.0.1
      lan10:
        ipv4_address: 10.0.10.1
      transit:
        ipv4_address: 10.0.0.2
    environment:
      - MY_ASN=64512
      - PEER_ASN=64513
      - PEER_IP=10.0.0.2
      - BGP_ROUTER_ID=192.168.0.1
      - ADVERTISE_PREFIXES=10.0.10.0/24
    logging:
      driver: "none"   # ← ログを一切残さない
      
  r2:
    networks:
      mgmtnet:
        ipv4_address: 192.168.0.2
      lan20:
        ipv4_address: 10.0.20.1
      transit:
        ipv4_address: 10.0.0.3
    environment:
      - MY_ASN=64513
      - PEER_ASN=64512
      - PEER_IP=10.0.0.2
      - BGP_ROUTER_ID=192.168.0.2
      - ADVERTISE_PREFIXES=10.0.20.0/24
    logging:
      driver: "none"   # ← ログを一切残さない

networks:
  mgmtnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.254
  lan10:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.254
  lan20:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.20.0/24
          gateway: 10.0.20.254
  transit:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/30
          gateway: 10.0.0.1

# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.common-4node.yml up -d --build
# Notes:
# - mgmtnet carries management addresses (192.168.0.1/2) and Router-ID.
# - transit (10.0.0.0/30) is the eBGP peering path (r1 .1 <-> r2 .2).
# - lan10 / lan20 (10.0.10.0/24, 10.0.20.0/24) are service segments advertised via BGP.
